# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Compatibility Testing

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Atlas Test Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Read .nvmrc and set environment variable
        id: read_nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: "Set up Node.js (${{ env.NODE_VERSION }})"
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      #- name: Run tests
      #  run: CI=true npm test --if-present
      - name: Build the application
        run: npm run build --if-present
